app-admin/eclean-kernel
app-admin/keepassxc
app-admin/sudo
app-admin/sysklogd
app-benchmarks/phoronix-test-suite
app-editors/emacs
app-editors/neovim
app-editors/vim
app-emulation/LookingGlass
app-emulation/qemu
app-emulation/virt-manager
app-emulation/winetricks
app-eselect/eselect-repository
app-i18n/fcitx-configtool::gentoo-zh
app-i18n/mozc::gentoo-zh
app-misc/abook
app-misc/anki
app-misc/neofetch
app-misc/piper
app-misc/radeontop
app-misc/screen
app-portage/cpuid2cpuflags
app-portage/eix
app-portage/genlop
app-portage/gentoolkit
app-portage/pfl
app-shells/gentoo-zsh-completions
app-shells/ksh
app-shells/tcsh
app-shells/zsh
app-shells/zsh-syntax-highlighting
app-text/doxygen
app-vim/gentoo-syntax
cross-i686-w64-mingw32/binutils
cross-i686-w64-mingw32/gcc
cross-i686-w64-mingw32/mingw64-runtime
cross-x86_64-w64-mingw32/binutils
cross-x86_64-w64-mingw32/gcc
cross-x86_64-w64-mingw32/mingw64-runtime
dev-build/cmake
dev-cpp/nlohmann_json
dev-debug/gdb
dev-debug/valgrind
dev-java/openjdk
dev-libs/boost
dev-libs/jemalloc
dev-libs/wayland
dev-python/pip
dev-qt/qt-creator
dev-qt/qtwayland
dev-scheme/racket
dev-util/cloc
dev-util/debugedit
dev-util/vulkan-tools
dev-vcs/git
games-util/lutris
games-util/steam-launcher
gui-apps/grim
gui-apps/hyprpaper
gui-apps/hyprpicker
gui-apps/rofi-wayland
gui-apps/slurp
gui-apps/swayidle
gui-apps/swaylock-effects
gui-apps/waybar
gui-apps/wl-clipboard
gui-libs/display-manager-init
gui-libs/xdg-desktop-portal-hyprland
gui-libs/xdg-desktop-portal-wlr
gui-wm/hyprland
kde-apps/ark
kde-apps/gwenview
kde-apps/kate
kde-apps/kcalc
kde-apps/kdenlive
kde-apps/kolourpaint
kde-apps/kruler
kde-apps/okular
kde-apps/spectacle
kde-misc/skanlite
mail-client/mutt-wizard
mail-client/neomutt
media-fonts/fira-mono
media-fonts/fira-sans
media-fonts/fonts-meta
media-fonts/hack
media-gfx/blender
media-gfx/gimp
media-gfx/inkscape
media-gfx/krita
media-gfx/plantuml
media-libs/libglvnd
media-libs/libpulse
media-libs/libsfml
media-libs/mesa
media-sound/elisa
media-sound/fluidsynth
media-sound/playerctl
media-sound/scream
media-tv/v4l-utils
media-video/amdgpu-pro-amf
media-video/obs-studio
media-video/pipewire
media-video/v4l2loopback
media-video/vlc
media-video/wireplumber
net-dns/avahi
net-ftp/filezilla
net-im/discord
net-irc/irssi
net-misc/adjtimex
net-misc/chrony
net-misc/keychain
net-misc/netifrc
net-print/cups
net-print/cups-meta
sys-apps/cpuid
sys-apps/fd
sys-apps/flatpak
sys-apps/hwinfo
sys-apps/hwloc
sys-apps/lm-sensors
sys-apps/lshw
sys-apps/mlocate
sys-apps/ripgrep
sys-apps/usbutils
sys-auth/google-authenticator
sys-auth/oath-toolkit
sys-auth/seatd
sys-block/gparted
sys-block/io-scheduler-udev-rules
sys-boot/grub
sys-boot/os-prober
sys-boot/unetbootin
sys-devel/crossdev
sys-firmware/intel-microcode
sys-fs/btrfs-progs
sys-fs/dosfstools
sys-fs/udisks
sys-kernel/gentoo-kernel
sys-kernel/installkernel
sys-kernel/linux-firmware
sys-libs/libhugetlbfs
sys-process/btop
sys-process/dcron
virtual/opengl
virtual/wine
www-client/firefox
www-client/firefox-bin
www-client/links
www-client/lynx
x11-apps/mesa-progs
x11-base/xorg-drivers
x11-base/xorg-server
x11-misc/copyq
x11-misc/dunst
x11-misc/qt5ct
x11-misc/zim
x11-terms/kitty
x11-themes/adwaita-qt
x11-wm/hypr
xfce-base/thunar
xfce-base/tumbler
